# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
  provider "aws" {
     region  = "us-east-2"
     profile = "default"
  }
  terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.0"
    }
}
  required_version = "~> 1.5.3"
  backend "s3" {}
  }
